name: branch-validator
on:
  push:
    branches-ignore:
      - master
      - develop
jobs:
  branch_validator:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to the world
        run: echo "hello, world!"
      - name: Cheking branch name
        run: |
          branch_name=${{ github.ref }}"
          echo "branch name: $branch_name"
          
          if [[ "$branch_name" =~ $branch_name ]]; then
            echo "Branch name matches the  regex pattern."
            if [[ "$target_branch" != "regex" ]]; then
              echo "but doesn't match target branch"
              exit 1
            fi
        shell: bash
