name: "Validate Branch Name"
description: "Ensure that a branch name conforms to a specific pattern"
branding:
  icon: "git-branch"
  color: "purple"
inputs:
  pattern:
    description: "Regex pattern that the branch name should match"
    required: true
    default: "[A-Z]{4,5}-[0-9]{4,5}-[A-Za-z]{5,30}"
runs:
  using: "node12"
  main: "dist/index.js"
