name: branch-validator

on:
  push:
    branches-ignore:
      - master


jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: goshencollege/validate-branch-name@v1.0.1
        with:
          pattern: "(master|develop|[A-Z]{4,5}-[0-9]{4,5}-[A-Za-z]{5,30})"
