name: branch-validator
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - "(master|develop|[A-Z]{4,5}-[0-9]{4,5}-[A-Za-z]{5,30})"


jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: goshencollege/validate-branch-name@v1.0.1
        with:
          pattern: "(master|develop|[A-Z]{4,5}-[0-9]{4,5}-[A-Za-z]{5,30})"

