name: branch-validator
on:
  create
  
jobs:
  branch_validator:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to the world
        run: echo "hello, world!"
      - name: Cheking branch name
        run: |
          branch_name=${{ github.ref_name }}
          echo "branch name: $branch_name"
          regex="(master|develop|[A-Z]{4,5}-[0-9]{4,5}-[A-Za-z]{5,30})"
          echo "regrex validotir: $regrex"
          echo "is equal $branch_name =~ $regex"
          if [[ $branch_name =~ $regex ]];
          then
            echo "correct branch name";
          else
            echo "Branch name does not match any regex. Exiting..."
            exit 1
          fi
        shell: bash
